package dev.legible.storage;

import java.util.List;

/**
 * Renders the R-map derivation as a Flyway base migration.
 *
 * <p><strong>Flyway owns DDL when an R-map/SQL store is used.</strong> The
 * schema is not applied at runtime; it is a versioned Flyway migration generated
 * from the same derivation the runtime store reads ({@link RmapDeriver} over the
 * Stage 02 concept {@code ## State}). This keeps one source of the table shape
 * and lets jOOQ codegen introspect the migration.
 *
 * <p>Deterministic: the same schemas render the same bytes, so a committed
 * migration can be checked for staleness (regenerate → compare). See
 * {@code reference-impl/java-micronaut/RELATIONAL_LOWERING.md}.
 *
 * <p>{@code TEXT} is rendered as {@code varchar}: jOOQ's {@code DDLDatabase}
 * parser (H2) maps it to {@code String} the same way, and the types are
 * equivalent on Postgres. {@code mandatory} is not rendered as {@code NOT NULL}
 * — the {@code Region} SPI writes one fact at a time, so a row-level constraint
 * would reject the first of several writes.
 */
public final class RmapMigration {

    private RmapMigration() {
    }

    /** The full migration text for {@code schemas}, headed for {@code appLabel}. */
    public static String render(String appLabel, List<RelationSchema> schemas) {
        StringBuilder sb = new StringBuilder();
        sb.append("-- Base DDL for ").append(appLabel).append(" concept state.\n");
        sb.append("--\n");
        sb.append("-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b\n");
        sb.append("-- conceptual data models via Halpin's R-map. Do NOT edit by hand:\n");
        sb.append("-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).\n");
        sb.append("--\n");
        sb.append("-- Fidelity: mandatory roles are not NOT NULL (the Region SPI writes one fact\n");
        sb.append("-- at a time); typed columns, DEFAULT for resettable facts, and UNIQUE are\n");
        sb.append("-- enforced, exactly as the R-map derivation specifies. TEXT is written as\n");
        sb.append("-- varchar here so jOOQ's DDLDatabase can introspect the schema.\n");
        for (RelationSchema schema : schemas) {
            sb.append("\n").append(createTable(schema)).append(";\n");
        }
        return sb.toString();
    }

    private static String createTable(RelationSchema schema) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE IF NOT EXISTS \"").append(schema.table()).append("\" (\n");
        sb.append("  \"").append(schema.idColumn()).append("\" varchar PRIMARY KEY");
        for (RelationSchema.Column col : schema.columns()) {
            sb.append(",\n  \"").append(col.column()).append("\" ")
                    .append(sqlType(col.sqlType()));
            if (col.defaultValue() != null) {
                sb.append(" DEFAULT ").append(col.defaultValue());
            }
            if (col.unique()) {
                sb.append(" UNIQUE");
            }
        }
        sb.append("\n)");
        return sb.toString();
    }

    private static String sqlType(String rmapType) {
        return switch (rmapType) {
            case "INTEGER" -> "integer";
            case "TIMESTAMP" -> "timestamp";
            default -> "varchar";
        };
    }
}
