-- Base DDL for Hold (domain fixture) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- R-map realises typed, keyed, constrained tables: NOT NULL (mandatory),
-- UNIQUE / PRIMARY KEY, CHECK (value constraints), FOREIGN KEY (intra-
-- concept references only — no cross-concept FK, R2). A concept whose
-- state ranges over several object types is a table set. TEXT is written
-- as varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "hold__member_and_copy" (
  "member" varchar NOT NULL,
  "copy" varchar NOT NULL,
  "hold" varchar,
  PRIMARY KEY ("member", "copy")
);
