-- Base DDL for UC-00-login (java-plain reference) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- R-map realises typed, keyed, constrained tables: NOT NULL (mandatory),
-- UNIQUE / PRIMARY KEY, CHECK (value constraints), FOREIGN KEY (intra-
-- concept references only — no cross-concept FK, R2). A concept whose
-- state ranges over several object types is a table set. TEXT is written
-- as varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "user_naming" (
  "user_id" varchar NOT NULL PRIMARY KEY,
  "username" varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "password_auth" (
  "user_id" varchar NOT NULL PRIMARY KEY,
  "password_hash" varchar NOT NULL,
  "failed_attempts" integer DEFAULT 0 NOT NULL,
  "locked_until" timestamp
);

CREATE TABLE IF NOT EXISTS "session" (
  "session_id" varchar NOT NULL PRIMARY KEY,
  "user_id" varchar NOT NULL,
  "opened_at" timestamp NOT NULL
);
