-- Base DDL for OrderIntake (domain fixture) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- R-map realises typed, keyed, constrained tables: NOT NULL (mandatory),
-- UNIQUE / PRIMARY KEY, CHECK (value constraints), FOREIGN KEY (intra-
-- concept references only — no cross-concept FK, R2). A concept whose
-- state ranges over several object types is a table set. TEXT is written
-- as varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "order_intake" (
  "order" varchar NOT NULL PRIMARY KEY,
  "order_number" varchar NOT NULL UNIQUE,
  "total_cents" integer DEFAULT 0 NOT NULL,
  "status" varchar NOT NULL,
  "placed_at" timestamp NOT NULL,
  CONSTRAINT ck_order_status CHECK (status IN ('open', 'paid', 'shipped'))
);

CREATE TABLE IF NOT EXISTS "order_intake__order_and_product" (
  "order" varchar NOT NULL,
  "product" varchar NOT NULL,
  "line" integer NOT NULL,
  PRIMARY KEY ("order", "product")
);

CREATE TABLE IF NOT EXISTS "order_intake__tags" (
  "order" varchar NOT NULL,
  "tags" varchar NOT NULL,
  PRIMARY KEY ("order", "tags"),
  FOREIGN KEY ("order") REFERENCES "order_intake" ("order")
);
