-- Base DDL for UC-00-login (java-micronaut reference) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- Fidelity: mandatory roles are not NOT NULL (the Region SPI writes one fact
-- at a time); typed columns, DEFAULT for resettable facts, and UNIQUE are
-- enforced, exactly as the R-map derivation specifies. TEXT is written as
-- varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "user_naming" (
  "user_id" varchar PRIMARY KEY,
  "username" varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS "password_auth" (
  "user_id" varchar PRIMARY KEY,
  "password_hash" varchar,
  "failed_attempts" integer DEFAULT 0,
  "locked_until" timestamp
);

CREATE TABLE IF NOT EXISTS "session" (
  "session_id" varchar PRIMARY KEY,
  "user_id" varchar,
  "opened_at" timestamp
);
