#!/usr/bin/env python3
"""
generate_review_views.py — emit Stage 03a's two derived review views:

  * `concept-matrix.md` — the FR×DP matrix (scenarios × concepts) plus the
    anti-pattern findings (God Object / duplication / entanglement). This
    supersedes the older `verify_concept_matrix.py --output` invocation for
    stage authoring: that form wrote the bare matrix without the findings,
    so the committed review artifact was missing the analysis it exists to
    carry.
  * `sync-information-profile.md` — the per-sync A/B/C/D binding profile
    and the feature aggregate (the Information-Axiom reading of
    SYNC_PATTERNS.md's ladder), with the D-read and wide-join prompts.

Both views are fully derived from the feature's approved Gate-1/Stage-03
artefacts — nothing in them is authored. Deterministic: the same inputs
render the same bytes, so a committed view can be drift-checked
(`--check`), the `shared-triggers.md` pattern.

Usage:
  python3 generate_review_views.py --feature <features/UC-XX-slug> --write
  python3 generate_review_views.py --feature <features/UC-XX-slug> --check
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sync_information as si  # noqa: E402
import verify_concept_matrix as vcm  # noqa: E402


def feature_paths(feature_root):
    root = os.path.abspath(feature_root)
    return {
        "usecase": os.path.join(root, "stages", "01_usecase", "output",
                                "usecase.md"),
        "chain_dir": os.path.join(root, "stages", "01b_chain-table", "output"),
        "resp_map": os.path.join(root, "stages", "01a_responsibility-map",
                                 "output", "responsibility-map.md"),
        "sync_dir": os.path.join(root, "stages", "03_syncs", "output"),
        "out_dir": os.path.join(root, "stages", "03a_dependency-review",
                                "output"),
    }


def render_concept_matrix(paths):
    """concept-matrix.md — the matrix plus the findings."""
    scenarios = vcm.extract_scenarios(paths["usecase"])
    concepts = vcm.extract_concepts(paths["resp_map"])
    matrix, coverage = vcm.build_matrix(scenarios, concepts, paths["chain_dir"])

    lines = [
        "# Concept matrix (FR×DP) — generated review view",
        "",
        "<!-- GENERATED by quality-gate/generate_review_views.py from the",
        "     feature's Gate-1 artefacts (usecase scenarios × responsibility-map",
        "     concepts, via the chain tables). Do NOT edit by hand: regenerate",
        "     (see Stage 03a's contract). Scenarios are the functional",
        "     requirements, concepts the design parameters (Suh's Independence",
        "     Axiom — see CITATIONS.md §Axiomatic Design). -->",
        "",
    ]
    if not scenarios or not concepts:
        lines += ["(no scenarios or concepts found — nothing to matrix)", ""]
        return "\n".join(lines)

    lines.append(f"{len(scenarios)} scenarios × {len(concepts)} concepts")
    lines.append("")
    lines.append("| Scenario | " + " | ".join(concepts) + " |")
    lines.append("|---|" + "|".join(":---:" for _ in concepts) + "|")
    for scenario in scenarios:
        cells = ["X" if matrix.get(scenario, {}).get(c) == "X" else "—"
                 for c in concepts]
        lines.append(f"| {scenario} | " + " | ".join(cells) + " |")
    lines.append("")

    god = vcm.detect_god_objects(coverage, len(scenarios))
    duplicates = vcm.detect_duplication(matrix, scenarios)
    entangled = vcm.detect_entanglement(matrix, scenarios)
    if not (god or duplicates or entangled):
        lines.append("No anti-pattern findings — the matrix above is the "
                     "review surface.")
    else:
        lines.append("## Findings (advisory — resolve at the responsibility "
                     "map or chain table)")
        lines.append("")
        for concept, count, total, ratio in god:
            lines.append(f"- **God Object:** `{concept}` touches "
                         f"{count}/{total} scenarios ({ratio:.0%}) — consider "
                         f"splitting it into smaller, focused concepts.")
        for c1, c2, shared in duplicates:
            lines.append(f"- **Duplication:** `{c1}` and `{c2}` cover the "
                         f"same scenarios — they may duplicate business "
                         f"logic; merge or clarify their distinct purposes.")
        for c1, c2, shared in entangled:
            lines.append(f"- **Entanglement:** `{c1}` and `{c2}` share "
                         f"{len(shared)} scenario(s) — the boundary between "
                         f"them may be unclear.")
    lines.append("")
    lines.append("NOTE: small, cohesive features (3-5 scenarios) naturally "
                 "have concepts that touch many scenarios — expected, not a "
                 "defect. Duplication flags are the most actionable.")
    lines.append("")
    return "\n".join(lines)


def render_sync_profile(paths):
    """sync-information-profile.md — per-sync A/B/C/D + aggregate + findings."""
    lines = [
        "# Sync information profile — generated review view",
        "",
        "<!-- GENERATED by quality-gate/generate_review_views.py from the",
        "     feature's 03_syncs output (each sync's where-pattern table).",
        "     Do NOT edit by hand: regenerate (see Stage 03a's contract).",
        "     The A/B/C/D ladder is an information-content reading of",
        "     SYNC_PATTERNS.md (the Information Axiom, adapted — see",
        "     CITATIONS.md §Axiomatic Design). The labels are author-declared,",
        "     so this profile is a self-report. -->",
        "",
    ]
    if not os.path.isdir(paths["sync_dir"]):
        lines += ["(no sync directory — nothing to profile)", ""]
        return "\n".join(lines)
    files = sorted(f for f in os.listdir(paths["sync_dir"])
                   if f.endswith(".sync.md"))
    if not files:
        lines += ["(no *.sync.md — nothing to profile)", ""]
        return "\n".join(lines)

    total = {"A": 0, "B": 0, "C": 0, "D": 0}
    findings = []
    lines.append(f"{len(files)} sync(s)")
    lines.append("")
    for fname in files:
        counts, conjuncts, d_sources, has_table = si.parse_sync(
            os.path.join(paths["sync_dir"], fname))
        stem = fname[:-len(".sync.md")]
        if not has_table:
            lines.append(f"- `{stem}`: no where-pattern table "
                         "(unresolved skeleton)")
            continue
        for k in total:
            total[k] += counts[k]
        lines.append(f"- `{stem}`: A={counts['A']} B={counts['B']} "
                     f"C={counts['C']} D={counts['D']} join={conjuncts}")
        for src in d_sources:
            findings.append(f"`{stem}`: D-read — outcome instead of read? "
                            "If this read decides something, the owning "
                            "concept could emit an outcome the sync routes "
                            "on (Pattern A) instead (concepts decide, syncs "
                            "route).")
        if conjuncts >= si._WIDE_JOIN:
            findings.append(f"`{stem}`: join arity {conjuncts} — real "
                            "coordination knowledge in one rule; check the "
                            "chain table intends it.")
    lines.append("")
    lines.append(f"Aggregate: A={total['A']} B={total['B']} C={total['C']} "
                 f"D={total['D']} ({sum(total.values())} bindings)")
    if si._D_BUDGET and total["D"] > si._D_BUDGET:
        findings.append(f"feature D-read budget exceeded: {total['D']} > "
                        f"{si._D_BUDGET} — every D is a place a concept could "
                        "decide instead; move reads into concept outcomes "
                        "or raise the budget with a recorded reason.")
    lines.append("")
    lines.append("Reading: A adds zero; B adds chain-topology knowledge; "
                 "C adds a copy point; D crosses a concept boundary.")
    lines.append("")
    if findings:
        lines.append("## Findings (advisory)")
        lines.append("")
        lines.extend(f"- {f}" for f in findings)
        lines.append("")
    else:
        lines.append("No advisory findings — the profile above is the "
                     "review surface.")
        lines.append("")
    return "\n".join(lines)


VIEWS = {
    "concept-matrix.md": render_concept_matrix,
    "sync-information-profile.md": render_sync_profile,
}


def main():
    parser = argparse.ArgumentParser(
        description="Emit (or drift-check) Stage 03a's derived review views")
    parser.add_argument("--feature", required=True, help="Feature root")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true",
                      help="Write the views (default: dry run)")
    mode.add_argument("--check", action="store_true",
                      help="Compare the committed views; exit 1 if stale")
    args = parser.parse_args()

    paths = feature_paths(args.feature)
    missing = [k for k, v in paths.items()
                if k != "out_dir" and not os.path.exists(v)]
    if missing:
        print(f"SKIP  inputs not present: {', '.join(missing)}")
        return 0

    stale = []
    for name, render in VIEWS.items():
        text = render(paths)
        path = os.path.join(paths["out_dir"], name)
        if args.check:
            if not os.path.isfile(path):
                stale.append(f"{name}: missing")
            elif open(path, encoding="utf-8").read() != text:
                stale.append(f"{name}: stale")
        elif args.write:
            os.makedirs(paths["out_dir"], exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
            print(f"WROTE {os.path.relpath(path, os.path.abspath(args.feature))}")
        else:
            print(f"WOULD WRITE {name} ({len(text)} bytes)")

    if args.check:
        if stale:
            print(f"FAIL  review view drift: {', '.join(stale)} — regenerate "
                  f"with generate_review_views.py --feature {args.feature} "
                  "--write")
            return 1
        print("PASS  review views current")
        return 0
    if not args.write:
        print("\nDry run. Re-run with --write to emit the views.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
