#!/usr/bin/env python3
"""
generate_sync_cards.py — deterministic Stage 03a dependency-review cards.

One `*-card.md` per concept (Section 1 = syncs whose `then` invokes this
concept; Section 2 = syncs whose `where` reads this concept's region, i.e.
Pattern D), plus a `pattern-d-summary.md`. This is an exact-token audit
produced mechanically from Stage 03 syncs — no new design, no repair.

The generator only copies what the syncs already declare. It never invents
a data source or normalizes a token.

Usage:
  python3 generate_sync_cards.py --feature <features/UC-XX-slug> [--write]
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Dict, List, Set

import artifact_parsers as ap
import clad_stages as cs


def main() -> None:
    parser = argparse.ArgumentParser(description="Deterministically generate Stage 03a cards")
    parser.add_argument("--feature", required=True, help="Feature root path")
    parser.add_argument("--write", action="store_true", help="Write files (default dry-run)")
    args = parser.parse_args()

    feature_root = os.path.abspath(args.feature)
    sync_dir = cs.SYNC_DIR(feature_root)
    dep_dir = cs.DEP_DIR(feature_root)
    resp_map = os.path.join(feature_root, "stages", "01a_responsibility-map",
                            "output", "responsibility-map.md")

    syncs = ap.parse_syncs(sync_dir)
    if not syncs:
        print("No syncs found — run generate_syncs.py first.")
        sys.exit(1)

    # concepts that appear in any sync's then-targets or triggers (Web included —
    # the bootstrap concept's `respond` action is a legitimate inbound invocation)
    concepts: Set[str] = set()
    for s in syncs:
        if s.trigger_concept:
            concepts.add(s.trigger_concept)
        for c, _a in s.then_targets:
            concepts.add(c)

    for concept in sorted(concepts):
        invocations: List[str] = []
        for s in syncs:
            for c, a in s.then_targets:
                if c == concept:
                    cited = ", ".join(s.cited_scenarios) or "<scenario>"
                    invocations.append(
                        f"| `{a}` | `{s.name}` ({cited}) | `<args>` | A | `<source>` |")

        reads: List[str] = []
        for s in syncs:
            if concept in s.pattern_d_concepts:
                reads.append(f"| `<field>` | `{s.name}` | `<scenario>` | `<id>` |")

        lines: List[str] = []
        lines.append("<!-- generated by generate_sync_cards.py — review, then fill <...> -->")
        lines.append(f"# Dependency review — `{concept}`")
        lines.append("")
        lines.append("## Section 1 — Invocations received")
        lines.append("")
        lines.append("| Action | Flow (sync) | Data received | Pattern | Source |")
        lines.append("|---|---|---|---|---|")
        if invocations:
            lines.extend(invocations)
        else:
            lines.append("| `<none>` | — | — | — | — |")
        lines.append("")
        lines.append("## Section 2 — Named-region reads by others (inbound Pattern D)")
        lines.append("")
        if reads:
            lines.append("| Field | Read by (sync) | In flow | Key |")
            lines.append("|---|---|---|---|")
            lines.extend(reads)
        else:
            lines.append("None — no other concept's sync reads "
                         f"`{concept}`'s named region.")
        lines.append("")
        lines.append("## Inconsistencies and risks")
        lines.append("")
        lines.append("- <review after filling `<args>`/`<source>`>")
        lines.append("")
        lines.append("## Cross-checks")
        lines.append("")
        lines.append(f"- Every `Action` row exists in `../../02_concepts/output/{concept}.concept.md`.")
        lines.append("- Every `Sync` named here exists in `../../03_syncs/output/`.")
        lines.append("")
        lines.append("**Do you agree with this card? Any corrections before I continue?**")

        out_path = os.path.join(dep_dir, concept + "-card.md")
        content = "\n".join(lines) + "\n"
        if args.write:
            os.makedirs(dep_dir, exist_ok=True)
            with open(out_path, "w") as fh:
                fh.write(content)
            print(f"WROTE {cs.relpath(out_path, feature_root)}")
        else:
            print(f"WOULD WRITE {concept}-card.md  "
                  f"({len(invocations)} invocations, {len(reads)} D-reads)")

    # pattern-d-summary.md
    d_rows: List[str] = []
    for s in syncs:
        for concept in s.pattern_d_concepts:
            cited = ", ".join(s.cited_scenarios) or "<scenario>"
            d_rows.append(f"| `{s.name}` | `<field>` | `{concept}` | `<id>` | {cited} |")
    summary_lines: List[str] = []
    summary_lines.append("<!-- generated by generate_sync_cards.py -->")
    summary_lines.append("# Concept-state reads — UC-00")
    summary_lines.append("")
    summary_lines.append("## Concept-state reads")
    summary_lines.append("")
    if d_rows:
        summary_lines.append("| Consumer (sync) | Field read | Owner concept | Key | In flow |")
        summary_lines.append("|---|---|---|---|---|")
        summary_lines.extend(d_rows)
    else:
        summary_lines.append("No concept-state reads in this feature.")
    summary_lines.append("")
    summary_lines.append("## Cross-flow inconsistencies")
    summary_lines.append("")
    summary_lines.append("- none")
    summary_lines.append("")

    out_path = os.path.join(dep_dir, "pattern-d-summary.md")
    content = "\n".join(summary_lines)
    if args.write:
        os.makedirs(dep_dir, exist_ok=True)
        with open(out_path, "w") as fh:
            fh.write(content)
        print(f"WROTE {cs.relpath(out_path, feature_root)}")
    else:
        print(f"WOULD WRITE pattern-d-summary.md  ({len(d_rows)} D-reads)")


if __name__ == "__main__":
    main()
