#!/usr/bin/env python3
"""
generate_contract.py — deterministic Stage 04b contract skeleton generation.

A contract is "derived mechanically from <Name>.concept.md: action signatures,
outcome enums, and flow-token shape" (templates/spec.md). This generator
produces one `<Name>.contract.md` per non-bootstrap concept with:

  * the action list from the concept spec (deterministic),
  * the outcome enums collected from the canonical chain tables — the source of
    truth for which outcomes each action actually emits (deterministic),
  * flow-token + input type TODO markers where the concept's rich signature
    requires judgment-free transcription the agent completes after generation.

It never invents an outcome, input type, or flow-token field.

Usage:
  python3 generate_contract.py --feature <features/UC-XX-slug> [--write]
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Dict, List, Set, Tuple

import artifact_parsers as ap
import clad_stages as cs


def collect_outcomes(feature_root: str) -> Dict[Tuple[str, str], Set[str]]:
    """{(concept, action): set(outcome_base)} from canonical chain tables."""
    out: Dict[Tuple[str, str], Set[str]] = {}
    chain_dir = cs.CHAIN_DIR(feature_root)
    if not os.path.isdir(chain_dir):
        return out
    for fname in sorted(os.listdir(chain_dir)):
        if not fname.endswith("-chain.md") or fname.endswith("-all-scenarios-chain.md"):
            continue
        for row in ap.parse_chain_table(os.path.join(chain_dir, fname)):
            out.setdefault((row.then_concept, row.then_action), set()).update(
                row.outcome_bases)
    return out


# `flow token: { action: "Concept.action", ..., outcome: "token" }`
FLOW_TOKEN_OUTCOME = re.compile(
    r'action:\s*"(\w+)\.(\w+)"[^}\n]*?outcome:\s*"([A-Za-z0-9_]+)"')


def collect_concept_outcomes(path: str) -> Dict[Tuple[str, str], Set[str]]:
    """{(concept, action): {OUTCOME}} from a concept spec's flow tokens.

    The canonical contract's outcome enums come from the CONCEPT, not from one
    feature's chain tables: a feature that merely extends a concept does not
    invoke its older actions, so chain-derived enums would silently drop them
    (UC-03 lost `enrol`'s and `acquire`'s outcomes)."""
    out: Dict[Tuple[str, str], Set[str]] = {}
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    for concept, action, outcome in FLOW_TOKEN_OUTCOME.findall(text):
        out.setdefault((concept, action), set()).add(
            ap.normalize_outcome(outcome))
    return out


def render_spec(concept: ap.ConceptSpec, outcomes: Dict[Tuple[str, str], Set[str]]) -> str:
    lines: List[str] = []
    lines.append("<!-- generated by generate_contract.py — review, then fill TODOs -->")
    lines.append(f"# {concept.name} — contract")
    lines.append("")
    lines.append("## Actions")
    lines.append("")
    for action in concept.actions:
        o = outcomes.get((concept.name, action.name), set())
        # Normalize PascalCase chain-table outcomes to SCREAMING_SNAKE_CASE so the
        # contract enum matches what verify_outcome_alignment.py expects (BAD_PASSWORD,
        # not BADPASSWORD). Reuses the same normalizer the check uses.
        enum = ", ".join(f"`{ap.normalize_outcome(x)}`" for x in sorted(o)) or "`<TODO>`"
        lines.append(f"### `{action.name}(...) -> <TODO>`")
        lines.append("")
        lines.append("- **Inputs:** `<TODO> — transcribe from concept spec`")
        lines.append(f"- **Outcomes (enum):** {enum}")
        lines.append(f"- **Flow token:** `<TODO> — transcribe from concept spec`")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Deterministically generate Stage 04b contracts")
    parser.add_argument("--feature", required=True, help="Feature root path")
    parser.add_argument("--write", action="store_true", help="Write files (default dry-run)")
    args = parser.parse_args()

    feature_root = os.path.abspath(args.feature)
    contract_dir = os.path.join(feature_root, "stages", "04_implement", "04b_contract", "output")

    # Concept sources: the feature's own proposals shadow the canonical corpus
    # by concept name (M1 union resolution).
    specs = ap.concept_spec_paths(cs.concept_source_dirs(feature_root))
    # The canonical contract lives with the canonical concept, so derive one
    # only for concepts this feature introduces or extends; a reused concept
    # binds the canonical contract. Apply the rule whenever the feature HAS a
    # responsibility map — an empty result means "no contracts", not "no
    # filter" (only a legacy map, with no `Origin` column, falls back to one
    # contract per concept).
    resp_map = os.path.join(feature_root, "stages", "01a_responsibility-map",
                            "output", "responsibility-map.md")
    if os.path.isfile(resp_map):
        wanted = set(cs.feature_contract_concepts(feature_root))
        specs = {n: p for n, p in specs.items() if n in wanted}
    if not specs:
        print("No concept directory found.")
        sys.exit(1)

    outcomes = collect_outcomes(feature_root)

    n = 0
    for name, path in sorted(specs.items()):
        concept = ap.parse_concept(path)
        if concept.name == "Web":  # bootstrap — no contract
            continue
        out_path = os.path.join(contract_dir, concept.name + ".contract.md")
        # Canonical enums: the concept's own flow tokens, unioned with this
        # feature's approved chain outcomes.
        merged = {k: set(v) for k, v in outcomes.items()}
        for key, values in collect_concept_outcomes(path).items():
            merged.setdefault(key, set()).update(values)
        content = render_spec(concept, merged)
        if args.write:
            os.makedirs(contract_dir, exist_ok=True)
            with open(out_path, "w") as fh:
                fh.write(content + "\n")
            print(f"WROTE {cs.relpath(out_path, feature_root)}")
        else:
            print(f"WOULD WRITE {concept.name}.contract.md  "
                  f"({len(concept.actions)} actions)")
        n += 1

    if not args.write:
        print(f"\n{n} contracts (dry run). Re-run with --write to emit files.")


if __name__ == "__main__":
    main()
