#!/usr/bin/env python3
"""
generate_feature_files.py — deterministic Stage 04c Gherkin .feature scaffold.

The .feature file is "the executable form of the use case", and much of its
shape IS mechanical (Feature header ← usecase H1/actor/operational principle;
one Scenario per ### Scenario:; response status codes ← sync specs; token-chain
comments ← chain-table rows). This generator emits that scaffold:

  * Feature header (`Feature:`, `As a`, `I want`, `So that`) from the use case
  * one Scenario stub per `### Scenario:` heading, with the derived token-chain
    comment and the response status asserted from the sync specs

It leaves the natural-language step text (`Given ...`, `When ...`, `And the
response body contains ...`) and Scenario Outline `Examples:` rows as TODO
placeholders — those come from prose the generator cannot invent.

Step-definition skeletons (.java) are NOT generated here: they are
profile-specific and the template marks them `@Disabled`; the agent writes them
from `templates/step-definitions.java` after this scaffold is approved.

Usage:
  python3 generate_feature_files.py --feature <features/UC-XX-slug> [--write]
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import List, Optional

import artifact_parsers as ap
import clad_stages as cs


def _token_chain_comment(chain_dir: str, scenario: str) -> str:
    """A comment line naming the chain-table token sequence for a scenario."""
    chain_file = os.path.join(chain_dir, scenario + "-chain.md")
    if not os.path.isfile(chain_file):
        return "#   <TODO: token chain — no chain table found for this scenario>"
    rows = ap.parse_chain_table(chain_file)
    tokens = []
    for r in rows:
        suffix = f"[{r.outcome_base}]" if r.outcome_base else ""
        tokens.append(f"{r.then_concept}.{r.then_action}{suffix}")
    return "#   " + " -> ".join(tokens)


def _scenario_status(chain_dir: str, scenario: str) -> Optional[int]:
    """The terminal Web.respond status for a scenario chain (row with then_suffix)."""
    chain_file = os.path.join(chain_dir, scenario + "-chain.md")
    if not os.path.isfile(chain_file):
        return None
    rows = ap.parse_chain_table(chain_file)
    for r in rows:
        if r.then_suffix is not None and r.then_concept == "Web":
            digits = re.search(r"\d+", r.then_suffix or "")
            if digits:
                return int(digits.group(0))
    return None


def build_feature(feature_root: str) -> Optional[str]:
    usecase_path = os.path.join(feature_root, "stages", "01_usecase", "output",
                                "usecase.md")
    chain_dir = cs.CHAIN_DIR(feature_root)

    if not os.path.isfile(usecase_path):
        print("FAIL  no usecase.md — run Stage 01 first.")
        return None

    uc_text = open(usecase_path).read()

    # Feature name: H1 after "# UC-.." or plain H1.
    title_m = re.search(r"^#\s+.*[—-]\s*(.+?)\s*$", uc_text, re.MULTILINE)
    feature_name = title_m.group(1).strip() if title_m else "<feature name>"

    # Primary actor: first non-Web actor bullet under ## Actors.
    # Handles `- Name — description` and `- **Name** — description`.
    actor = "<actor>"
    m = re.search(r"#{2,3}\s+Actors?\s*\n(.*?)(?=#{2,3}|\Z)", uc_text, re.DOTALL)
    if m:
        for line in m.group(1).splitlines():
            t = line.strip().lstrip("- ").strip()
            if not t:
                continue
            m_bold = re.match(r"\*\*(.+?)\*\*", t)
            if m_bold:
                t = m_bold.group(1).strip()
            else:
                t = t.split("—", 1)[0].strip()
            if t and not t.lower().startswith(("web", "system")):
                actor = t
                break

    scenarios = sorted(ap.parse_scenario_names(usecase_path))

    feature_slug = os.path.basename(feature_root.rstrip("/"))
    uc_num_m = re.search(r"UC-(\d+)", feature_slug)
    uc_tag = f"@UC-{uc_num_m.group(1)}" if uc_num_m else "@UC-XX"

    L: List[str] = []
    add = L.append
    add(f"# Derived from: usecase.md  (scaffold generated by generate_feature_files.py)")
    add(f"{uc_tag} @{ap.slugify(feature_name)}")
    add(f"Feature: {feature_name}")
    add("")
    add(f"  As a {actor}")
    # The "I want"/"So that" phrasing is a prose condensing of the operational
    # principle — genuine judgement. Emit TODOs; do not guess the wording.
    add(f"  I want <TODO: goal — first sentence of operational principle>")
    add(f"  So that <TODO: rationale — remainder of operational principle>")
    add("")
    add("  Background:")
    add("    Given the system is running")
    add("")

    status_flip = {"happy-path", "failure-path"}
    for i, sc in enumerate(scenarios):
        status = _scenario_status(chain_dir, sc)
        add(f"  # Scenario {i+1} — TODO: confirm happy/failure path tag")
        add(_token_chain_comment(chain_dir, sc))
        tag = "@happy-path" if status and status < 400 else "@failure-path"
        add(f"  @{ap.slugify(sc)} {tag}")
        add(f"  Scenario: TODO — scenario title for `<{sc}>`")
        add(f"    Given <TODO: {sc} precondition(s)>")
        add(f"    When <TODO: {sc} trigger — main-flow step 1>")
        if status is not None:
            add(f"    Then the response status is {status}")
        else:
            add(f"    Then the response status is <TODO: derive from sync specs>")
        add(f"    And the response body matches <TODO: {sc} expected body shape>")
        add("")
    return "\n".join(L)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Deterministically generate Stage 04c Gherkin scaffold")
    parser.add_argument("--feature", required=True, help="Feature root path")
    parser.add_argument("--write", action="store_true",
                        help="Write files (default dry-run)")
    args = parser.parse_args()

    feature_root = os.path.abspath(args.feature)
    out_dir = os.path.join(feature_root, "stages", "04_implement",
                           "04c_flow-tests", "output")
    feature_name = os.path.basename(feature_root.rstrip("/"))
    # prefer the usecase-derived name for the filename
    usecase_path = os.path.join(feature_root, "stages", "01_usecase", "output",
                                "usecase.md")
    fname = "flow.feature"
    if os.path.isfile(usecase_path):
        base = ap.slugify(feature_name.replace("UC-", "", 1))
        fname = (base or "flow") + ".feature"

    content = build_feature(feature_root)
    if content is None:
        sys.exit(1)

    out_path = os.path.join(out_dir, fname)
    if args.write:
        os.makedirs(out_dir, exist_ok=True)
        with open(out_path, "w") as fh:
            fh.write(content + "\n")
        print(f"WROTE {cs.relpath(out_path, feature_root)}")
    else:
        print(f"WOULD WRITE {fname}  (scaffold)")
        print("--- preview ---")
        print(content)
        print("--- run with --write to emit ---")


if __name__ == "__main__":
    main()
