#!/usr/bin/env python3
"""
generate_spec.py — deterministic Stage 04b SPEC skeleton generation.

A SPEC is "derived mechanically from <Name>.concept.md: action signatures,
outcome enums, and flow-token shape" (templates/spec.md). This generator
produces one `<Name>.spec.md` per non-bootstrap concept with:

  * the action list from the concept spec (deterministic),
  * the outcome enums collected from the canonical chain tables — the source of
    truth for which outcomes each action actually emits (deterministic),
  * flow-token + input type TODO markers where the concept's rich signature
    requires judgment-free transcription the agent completes after generation.

It never invents an outcome, input type, or flow-token field.

Usage:
  python3 generate_spec.py --feature <features/UC-XX-slug> [--write]
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Dict, List, Set, Tuple

import artifact_parsers as ap
import clad_stages as cs


def collect_outcomes(feature_root: str) -> Dict[Tuple[str, str], Set[str]]:
    """{(concept, action): set(outcome_base)} from canonical chain tables."""
    out: Dict[Tuple[str, str], Set[str]] = {}
    chain_dir = cs.CHAIN_DIR(feature_root)
    if not os.path.isdir(chain_dir):
        return out
    for fname in sorted(os.listdir(chain_dir)):
        if not fname.endswith("-chain.md") or fname.endswith("-all-scenarios-chain.md"):
            continue
        for row in ap.parse_chain_table(os.path.join(chain_dir, fname)):
            out.setdefault((row.then_concept, row.then_action), set()).add(row.outcome_base)
    return out


def render_spec(concept: ap.ConceptSpec, outcomes: Dict[Tuple[str, str], Set[str]]) -> str:
    lines: List[str] = []
    lines.append("<!-- generated by generate_spec.py — review, then fill TODOs -->")
    lines.append(f"# {concept.name} — SPEC")
    lines.append("")
    lines.append("## Actions")
    lines.append("")
    for action in concept.actions:
        o = outcomes.get((concept.name, action.name), set())
        enum = ", ".join(f"`{x.upper()}`" for x in sorted(o)) or "`<TODO>`"
        lines.append(f"### `{action.name}(...) -> <TODO>`")
        lines.append("")
        lines.append("- **Inputs:** `<TODO> — transcribe from concept spec`")
        lines.append(f"- **Outcomes (enum):** {enum}")
        lines.append(f"- **Flow token:** `<TODO> — transcribe from concept spec`")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Deterministically generate Stage 04b SPECs")
    parser.add_argument("--feature", required=True, help="Feature root path")
    parser.add_argument("--write", action="store_true", help="Write files (default dry-run)")
    args = parser.parse_args()

    feature_root = os.path.abspath(args.feature)
    concept_dir = cs.CONCEPT_DIR(feature_root)
    spec_dir = os.path.join(feature_root, "stages", "04_implement", "04b_spec", "output")

    if not os.path.isdir(concept_dir):
        print("No concept directory found.")
        sys.exit(1)

    outcomes = collect_outcomes(feature_root)

    n = 0
    for fname in sorted(os.listdir(concept_dir)):
        if not fname.endswith(".concept.md"):
            continue
        concept = ap.parse_concept(os.path.join(concept_dir, fname))
        if concept.name == "Web":  # bootstrap — no SPEC
            continue
        out_path = os.path.join(spec_dir, concept.name + ".spec.md")
        content = render_spec(concept, outcomes)
        if args.write:
            os.makedirs(spec_dir, exist_ok=True)
            with open(out_path, "w") as fh:
                fh.write(content + "\n")
            print(f"WROTE {cs.relpath(out_path, feature_root)}")
        else:
            print(f"WOULD WRITE {concept.name}.spec.md  "
                  f"({len(concept.actions)} actions)")
        n += 1

    if not args.write:
        print(f"\n{n} SPECs (dry run). Re-run with --write to emit files.")


if __name__ == "__main__":
    main()
