#!/usr/bin/env python3
"""
generate_data_model.py — deterministic Stage 03b conceptual-data-model skeleton.

The CSDP is judgement-laden, so this generator does NOT solve it. It emits the
full seven-step structure and auto-fills the parts that ARE mechanical from the
concept `## State` annotations:

  * Step 2 Object types — Entity types from each relation's SubjectType, Value
    types from each relation's value type.
  * Step 2 Fact types — one per `field` relation.
  * Step 4/5 uniqueness + mandatory roles — auto-derived only when the state
    line carries a `-- mandatory` / `-- optional` / `-- unique` annotation;
    otherwise the subsection is left as a `<TODO: judgment>` marker.

Steps 1 (familiar examples), 3 (combination/arithmetic derivations), 6
(value/set/subtype constraints), and 7 (final checks) are genuine judgement and
are always emitted as TODO skeleton — never guessed.

The output satisfies verify_data_model.py by construction (all headings +
subsections present, no storage leakage, no cross-concept entity names).

Usage:
  python3 generate_data_model.py --feature <features/UC-XX-slug> [--write]
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import List

import artifact_parsers as ap
import clad_stages as cs


def _is_mandatory(r: ap.StateRelation) -> bool:
    a = r.multiplicity.lower()
    return "mandatory" in a and "optional" not in a and "zero or more" not in a


def render(concept: ap.ConceptSpec) -> str:
    rels = ap.parse_state_relations(concept.state_lines)
    name = concept.name

    if not rels:
        return _render_stateless(name)

    entity_types = sorted({r.subject_type for r in rels if r.subject_type})
    value_types = sorted({r.value_type for r in rels if r.value_type})
    fact_types = [r.field for r in rels]
    unique_rels = [r.field for r in rels if r.unique]
    mandatory_rels = [r.field for r in rels if _is_mandatory(r)]
    optional_rels = [r.field for r in rels if not _is_mandatory(r)]
    annotated = any(r.multiplicity for r in rels)

    L: List[str] = []
    add = L.append

    add("<!-- generated by generate_data_model.py — review, then resolve <TODO> items -->")
    add(f"# {name} — conceptual data model")
    add("")
    add("## Step 1 — Familiar examples and elementary facts")
    add("")
    add("### Familiar examples")
    add("")
    add("- <TODO: judgment — example sentence from the approved state section>")
    add("")
    add("### Elementary facts")
    add("")
    for r in rels:
        add(f"- <TODO: judgment — elementary fact for `{r.field}`>")
    add("")
    add("### Step 1 quality checks")
    add("")
    add("- <TODO: judgment — object identification check>")
    add("- <TODO: judgment — split/recombine check>")
    add("")
    add("## Step 2 — Draft fact model and population check")
    add("")
    add("### Object types")
    add("")
    for e in entity_types:
        add(f"- Entity: `{e}`")
    for v in value_types:
        if v not in entity_types:
            add(f"- Value: `{v}`")
    add("")
    add("### Fact types")
    add("")
    for f in fact_types:
        add(f"- `{f}`")
    add("")
    add("### Population check")
    add("")
    add("- <TODO: judgment — at least one example populates each fact type>")
    add("")
    add("## Step 3 — Combination and arithmetic derivation checks")
    add("")
    add("### Entity-type combination check")
    add("")
    add("- <TODO: judgment — combined entity types, or `None`>")
    add("")
    add("### Arithmetic derivations")
    add("")
    add("- <TODO: judgment — derivable quantity/count, or `None`>")
    add("")
    add("## Step 4 — Uniqueness constraints and arity checks")
    add("")
    add("### Uniqueness constraints")
    add("")
    if annotated:
        if unique_rels:
            for f in unique_rels:
                add(f"- `{f}` is unique")
        else:
            add("- None")
    else:
        add("- <TODO: judgment — no state `-- unique` annotation; cannot auto-derive>")
    add("")
    add("### Arity checks")
    add("")
    add("- <TODO: judgment — arity of each fact type>")
    add("")
    add("## Step 5 — Mandatory roles and logical derivations")
    add("")
    add("### Mandatory role constraints")
    add("")
    if annotated:
        for f in mandatory_rels:
            add(f"- `{f}` is mandatory")
        for f in optional_rels:
            add(f"- `{f}` is optional")
    else:
        add("- <TODO: judgment — no `-- mandatory`/`-- optional` annotation; cannot auto-derive>")
    add("")
    add("### Logical derivations")
    add("")
    add("- <TODO: judgment — logical derivation rule, or `None`>")
    add("")
    add("## Step 6 — Value, set comparison, and subtype constraints")
    add("")
    add("### Value constraints")
    add("")
    add("- <TODO: judgment — value constraint, or `None`>")
    add("")
    add("### Set comparison constraints")
    add("")
    add("- <TODO: judgment — subset/equality/exclusion constraint, or `None`>")
    add("")
    add("### Subtype constraints")
    add("")
    add("- <TODO: judgment — subtype constraint, or `None`>")
    add("")
    add("## Step 7 — Other constraints and final checks")
    add("")
    add("### Other constraints")
    add("")
    add("- <TODO: judgment — other constraint, or `None`>")
    add("")
    add("### Final checks")
    add("")
    add("- <TODO: judgment — consistency with approved concept state>")
    add("- <TODO: judgment — redundancy or completeness note>")
    add("")
    add("## Modeling Notes")
    add("")
    add("- <TODO: judgment — non-obvious modeling decision, or `No notable decisions.`>")

    return "\n".join(L)


def _render_stateless(name: str) -> str:
    L: List[str] = []
    add = L.append
    add("<!-- generated by generate_data_model.py -->")
    add(f"# {name} — conceptual data model")
    add("")
    add("## Step 1 — Familiar examples and elementary facts")
    add("")
    add("### Familiar examples")
    add("")
    add(f"- None — `{name}` is stateless.")
    add("")
    add("### Elementary facts")
    add("")
    add(f"- None — `{name}` is stateless.")
    add("")
    add("### Step 1 quality checks")
    add("")
    add("- None — no state to check.")
    add("")
    add("## Step 2 — Draft fact model and population check")
    add("")
    add("### Object types")
    add("")
    add("- None")
    add("")
    add("### Fact types")
    add("")
    add("- None")
    add("")
    add("### Population check")
    add("")
    add("- None — no fact types.")
    add("")
    add("## Step 3 — Combination and arithmetic derivation checks")
    add("")
    add("### Entity-type combination check")
    add("")
    add("- None")
    add("")
    add("### Arithmetic derivations")
    add("")
    add("- None")
    add("")
    add("## Step 4 — Uniqueness constraints and arity checks")
    add("")
    add("### Uniqueness constraints")
    add("")
    add("- None")
    add("")
    add("### Arity checks")
    add("")
    add("- None")
    add("")
    add("## Step 5 — Mandatory roles and logical derivations")
    add("")
    add("### Mandatory role constraints")
    add("")
    add("- None")
    add("")
    add("### Logical derivations")
    add("")
    add("- None")
    add("")
    add("## Step 6 — Value, set comparison, and subtype constraints")
    add("")
    add("### Value constraints")
    add("")
    add("- None")
    add("")
    add("### Set comparison constraints")
    add("")
    add("- None")
    add("")
    add("### Subtype constraints")
    add("")
    add("- None")
    add("")
    add("## Step 7 — Other constraints and final checks")
    add("")
    add("### Other constraints")
    add("")
    add("- None")
    add("")
    add("### Final checks")
    add("")
    add(f"- Confirmed: `{name}` is stateless; no conceptual data model required.")
    add("")
    add("## Modeling Notes")
    add("")
    add("- Stateless concept — no fact model.")
    return "\n".join(L)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Deterministically generate Stage 03b conceptual data models")
    parser.add_argument("--feature", required=True, help="Feature root path")
    parser.add_argument("--write", action="store_true",
                        help="Write files (default dry-run)")
    args = parser.parse_args()

    feature_root = os.path.abspath(args.feature)
    concept_dir = cs.CONCEPT_DIR(feature_root)
    data_dir = cs.DATA_DIR(feature_root)

    if not os.path.isdir(concept_dir):
        print("No concept directory found.")
        sys.exit(1)

    n = 0
    for fname in sorted(os.listdir(concept_dir)):
        if not fname.endswith(".concept.md"):
            continue
        concept = ap.parse_concept(os.path.join(concept_dir, fname))
        if concept.name == "Web":  # bootstrap — no data model
            continue
        out_path = os.path.join(data_dir, concept.name + ".data-model.md")
        content = render(concept)
        if args.write:
            os.makedirs(data_dir, exist_ok=True)
            with open(out_path, "w") as fh:
                fh.write(content + "\n")
            print(f"WROTE {cs.relpath(out_path, feature_root)}")
        else:
            rels = len(ap.parse_state_relations(concept.state_lines))
            print(f"WOULD WRITE {concept.name}.data-model.md  ({rels} relations)")
        n += 1

    if not args.write:
        print(f"\n{n} data models (dry run). Re-run with --write to emit files.")


if __name__ == "__main__":
    main()
