#!/usr/bin/env python3
"""
generate_shared_triggers.py — deterministic cross-UC shared-trigger index.

Why this exists:
  Concepts are system-scope, so two use cases can legitimately fire a sync on
  the SAME `Concept.action` completion (maintenance change
  `system-scope-concept-vocabulary`). Stage 03/03a should see that before
  introducing a duplicate trigger. This is the cross-UC shared-trigger view.

It is ADVISORY: it is a generated index, not a gate. It records what the sync
specs already declare; it never repairs or normalizes a token.

Output: `features/_system/shared-triggers.md`

Usage:
  python3 generate_shared_triggers.py [--features-dir features] [--write]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

WHEN_BLOCK = re.compile(r"when\s*\{(.*?)\}", re.DOTALL)
CONJUNCT = re.compile(
    r"([A-Za-z]\w*)\s*/\s*([A-Za-z]\w*)\s*:\s*\[[^\]]*\]\s*=>\s*\[\s*([A-Za-z]\w*)")


def triggers_in(path):
    """Set of (Concept, action, outcome) declared in one sync file."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    found = set()
    for block in WHEN_BLOCK.findall(text):
        for concept, action, outcome in CONJUNCT.findall(block):
            found.add((concept, action, outcome))
    return found


def collect(features_dir):
    """trigger -> {(feature, sync_stem)}."""
    index = {}
    if not os.path.isdir(features_dir):
        return index
    for feature in sorted(os.listdir(features_dir)):
        if not feature.startswith("UC-"):
            continue
        sync_dir = os.path.join(features_dir, feature, "stages", "03_syncs", "output")
        if not os.path.isdir(sync_dir):
            continue
        for fname in sorted(os.listdir(sync_dir)):
            if not fname.endswith(".sync.md"):
                continue
            for trigger in triggers_in(os.path.join(sync_dir, fname)):
                index.setdefault(trigger, set()).add((feature, fname[:-len(".sync.md")]))
    return index


def render(features_dir):
    index = collect(features_dir)
    lines = [
        "# Shared triggers — cross-UC view",
        "",
        "> GENERATED by `quality-gate/generate_shared_triggers.py` from every",
        "> feature's `03_syncs/output/*.sync.md`. ADVISORY: consult it before",
        "> introducing a trigger another use case already fires, so a duplicate",
        "> trigger with divergent routing is a deliberate choice (see Stage 03a's",
        "> coordination review). Not a gate — do not hand-edit.",
        "",
        "| Trigger | Outcome | Features | Syncs |",
        "|---|---|---|---|",
    ]
    for (concept, action, outcome) in sorted(index):
        users = index[(concept, action, outcome)]
        features = ", ".join(sorted({f for f, _ in users}))
        syncs = ", ".join(f"`{s}`" for _, s in sorted(users))
        lines.append(f"| `{concept}.{action}` | `{outcome}` | {features} | {syncs} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the cross-UC shared-trigger index")
    parser.add_argument("--features-dir", default="features")
    parser.add_argument("--write", action="store_true",
                        help="Write the index (default: dry run)")
    args = parser.parse_args()

    content = render(args.features_dir)
    out_path = os.path.join(args.features_dir, "_system", "shared-triggers.md")
    if args.write:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"WROTE {out_path}")
    else:
        print(content)
        print(f"(dry run — pass --write to update {out_path})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
