#!/usr/bin/env python3
"""
generate_concepts_catalog.py — deterministic system-scope concept catalog.

Derives `features/_system/concepts-catalog.md` from the canonical corpus at
`features/_system/concepts/*.concept.md` (maintenance change
`system-scope-concept-vocabulary`, decision D3).

Why this exists:
  Concept specs are canonical, system-scope assets; use cases COMPOSE them.
  Stage 01a must be able to ask "does the action I need already exist?" without
  opening every full spec. The catalog is that index — and because it is
  derived, it can never disagree with the corpus. It is NEVER hand-edited:
  edit the corpus, re-run the generator.

Columns (deterministic, sorted by concept name):

  * Concept / Purpose / Type params / Actions  ← the concept file (anatomy).
  * Introduced by                              ← the `introduced-by` provenance line.
  * Used by                                    ← features whose Stage 02 output
                                                 binds the concept (Model B
                                                 `concept-bindings.md`) or, for
                                                 a pre-migration feature, still
                                                 carries a `<Name>.concept.md`
                                                 copy.
  * Notes                                      ← derived flags (e.g. `stateless`).

Usage:
  python3 generate_concepts_catalog.py [--concepts-dir features/_system/concepts] \
                                      [--features-dir features] [--write]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import artifact_parsers as ap  # noqa: E402

HEADER = re.compile(r"^concept\s+(\w+)\s*(?:\[([^\]]*)\])?")
PROVENANCE = re.compile(r"^introduced-by\s+(.+?)\s*$", re.MULTILINE)
STATELESS = re.compile(r"\*None\.\*\s+\w+\s+is stateless\.", re.IGNORECASE)

CATALOG_HEADER = (
    "> GENERATED by `quality-gate/generate_concepts_catalog.py` from\n"
    "> `features/_system/concepts/*.concept.md`. Do NOT edit this file by hand —\n"
    "> edit the canonical concept spec and re-run the generator."
)


def parse_purpose(text: str) -> str:
    """The `purpose` stanza: the indented line(s) following the bare `purpose`."""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.strip().lower() == "purpose":
            parts = []
            for nxt in lines[i + 1:]:
                stripped = nxt.strip()
                if not stripped or stripped.startswith("#") or stripped.startswith("```"):
                    break
                parts.append(stripped)
            return " ".join(parts).strip()
    return ""


def parse_concept_file(path: str):
    """Return (name, type_params, purpose, actions, introduced_by, stateless)."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    name, type_params = "", ""
    for line in text.split("\n"):
        m = HEADER.match(line.strip())
        if m:
            name = m.group(1)
            type_params = (m.group(2) or "").strip()
            break

    prov = PROVENANCE.search(text)
    actions = sorted({a.name for a in ap.parse_concept(path).actions})
    return (
        name,
        type_params,
        parse_purpose(text),
        actions,
        prov.group(1).strip() if prov else "",
        bool(STATELESS.search(text)),
    )


def collect_used_by(features_dir: str, concept: str, introducer: str):
    """Features that use the concept: the introducer, plus any feature whose
    Stage 02 output binds it or (pre-migration) still carries a spec copy."""
    users = set()
    if introducer:
        users.add(introducer)
    if not os.path.isdir(features_dir):
        return sorted(users)
    for feat in sorted(os.listdir(features_dir)):
        if feat.startswith("_") or not feat.startswith("UC-"):
            continue
        spec_dir = os.path.join(features_dir, feat, "stages", "02_concepts", "output")
        if not os.path.isdir(spec_dir):
            continue
        if os.path.isfile(os.path.join(spec_dir, concept + ".concept.md")):
            users.add(feat)
            continue
        bindings = os.path.join(spec_dir, "concept-bindings.md")
        if os.path.isfile(bindings):
            with open(bindings, encoding="utf-8") as fh:
                if re.search(rf"\b{re.escape(concept)}\b", fh.read()):
                    users.add(feat)
    return sorted(users)


def render(concepts_dir: str, features_dir: str) -> str:
    if not os.path.isdir(concepts_dir):
        return ""
    rows = []
    for fname in sorted(os.listdir(concepts_dir)):
        if not fname.endswith(".concept.md"):
            continue
        path = os.path.join(concepts_dir, fname)
        name, tparams, purpose, actions, introducer, stateless = parse_concept_file(path)
        if not name:
            continue
        used_by = collect_used_by(features_dir, name, introducer)
        rows.append({
            "concept": name,
            "purpose": purpose,
            "tparams": tparams,
            "actions": ", ".join(f"`{a}`" for a in actions),
            "introduced": introducer or "—",
            "used": ", ".join(used_by) if used_by else "—",
            "notes": "stateless" if stateless else "—",
        })

    def esc(s: str) -> str:
        return s.replace("|", "\\|") if s else "—"

    out = [
        "# Concepts catalog",
        "",
        CATALOG_HEADER,
        "",
        "| Concept | Purpose | Type params | Actions | Introduced by | Used by | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| `{r['concept']}` | {esc(r['purpose'])} | {esc(r['tparams'])} | "
            f"{r['actions'] or '—'} | {esc(r['introduced'])} | {esc(r['used'])} | "
            f"{esc(r['notes'])} |"
        )
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the system-scope concept catalog index")
    parser.add_argument("--concepts-dir", default="features/_system/concepts")
    parser.add_argument("--features-dir", default="features")
    parser.add_argument("--write", action="store_true",
                        help="Write the catalog (default: dry run)")
    args = parser.parse_args()

    content = render(args.concepts_dir, args.features_dir)
    if not content:
        print(f"No concept corpus found at {args.concepts_dir} — nothing to generate.")
        return 0

    out_path = os.path.join(os.path.dirname(args.concepts_dir), "concepts-catalog.md")
    if args.write:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"WROTE {out_path}")
    else:
        print(content)
        print(f"(dry run — pass --write to update {out_path})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
