-- Base DDL for PatientRegistry (domain fixture) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- R-map realises typed, keyed, constrained tables: NOT NULL (mandatory),
-- UNIQUE / PRIMARY KEY, CHECK (value constraints), FOREIGN KEY (intra-
-- concept references only — no cross-concept FK, R2). A concept whose
-- state ranges over several object types is a table set. TEXT is written
-- as varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "patient_registry__person" (
  "person" varchar NOT NULL PRIMARY KEY,
  "registered_at" timestamp NOT NULL,
  "gender" varchar NOT NULL,
  CONSTRAINT ck_person_gender CHECK (gender IN ('M', 'F'))
);

CREATE TABLE IF NOT EXISTS "patient_registry__patient" (
  "person" varchar NOT NULL PRIMARY KEY,
  "insurer_name" varchar,
  FOREIGN KEY ("person") REFERENCES "patient_registry__person" ("person")
);
