-- Base DDL for Scheduling (domain fixture) concept state.
--
-- GENERATED by dev.legible.storage.RmapMigration from the Stage 03b
-- conceptual data models via Halpin's R-map. Do NOT edit by hand:
-- regenerate after a concept `## State` change (see RELATIONAL_LOWERING.md).
--
-- R-map realises typed, keyed, constrained tables: NOT NULL (mandatory),
-- UNIQUE / PRIMARY KEY, CHECK (value constraints), FOREIGN KEY (intra-
-- concept references only — no cross-concept FK, R2). A concept whose
-- state ranges over several object types is a table set. TEXT is written
-- as varchar here so jOOQ's DDLDatabase can introspect the schema.

CREATE TABLE IF NOT EXISTS "scheduling__physician_and_patient_and_timeslot" (
  "physician" varchar NOT NULL,
  "patient" varchar NOT NULL,
  "timeslot" varchar NOT NULL,
  "appt" varchar NOT NULL,
  PRIMARY KEY ("physician", "patient", "timeslot"),
  CONSTRAINT ck_physician_and_patient_and_timeslot_appt CHECK (appt IN ('booked', 'seen', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS "scheduling__physician_and_patient" (
  "physician" varchar NOT NULL,
  "patient" varchar NOT NULL,
  "consult_fee" integer,
  PRIMARY KEY ("physician", "patient")
);

CREATE TABLE IF NOT EXISTS "scheduling__referral_source" (
  "referral_source" varchar NOT NULL PRIMARY KEY
);
