micronaut:
  router:
    static-resources:
      public:
        paths: classpath:public
        mapping: /**

datasources:
  default:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/clad}
    username: ${PGUSER:clad}
    password: ${PGPASSWORD:clad}
    driver-class-name: org.postgresql.Driver
